detectors:
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  DataClump:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    max_params: 5
  RepeatedConditional:
    max_ifs: 5
  TooManyMethods:
    max_methods: 30
  TooManyStatements:
    max_statements: 50
  TooManyConstants:
    max_constants: 10
  # NOTE: We prefer rubocop linter
  # https://rubocop.readthedocs.io/en/latest/cops_naming/#namingrescuedexceptionsvariablename
  UncommunicativeVariableName:
    accept:
      - e
      - _
directories:
  'app/clients':
    DuplicateMethodCall:
      allow_calls:
        - 'Rails.logger'
    NestedIterators:
      max_allowed_nesting: 2
    RepeatedConditional:
      enabled: false
  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    NilCheck:
      enabled: false
    TooManyInstanceVariables:
      max_instance_variables: 12
    UncommunicativeModuleName:
      enabled: false
    DuplicateMethodCall:
      allow_calls:
        - 'Rails.cache'
        - 'logger.error'
        - 'logger.warn'
        - 'logger.info'
        - 'logger.debug'
  'app/helpers':
    NestedIterators:
      max_allowed_nesting: 2
    IrresponsibleModule:
      enabled: false
    NilCheck:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/jobs':
    DuplicateMethodCall:
      allow_calls:
        - 'Rails.logger'
    NestedIterators:
      max_allowed_nesting: 2
    RepeatedConditional:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/models':
    DuplicateMethodCall:
      allow_calls:
        - 'Rails.logger'
    NestedIterators:
      max_allowed_nesting: 2
    RepeatedConditional:
      enabled: false
    TooManyInstanceVariables:
      max_instance_variables: 2
    InstanceVariableAssumption:
      enabled: false
  'app/models/concerns':
    UtilityFunction:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false
  'app/validators':
    UtilityFunction:
      enabled: false
