version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: root
    ports:
      - '5432:5432'
  api:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
    volumes:
      - bundle_install:/usr/local/bundle
      - .:/coko-api
    ports:
      - '3000:3000'
    links:
      - db
volumes:
  bundle_install: