default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: coko_api_development

test:
  <<: *default
  database: coko_api_test

production:
  <<: *default
  adapter: mysql2
  database: <%= ENV['DATABASE_URL'] %> # coko_api_production
  username: <%= ENV['DB_USERNAME'] %> # coko_api
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
